"""
Denoised Equilibrium Price · 2026 — the retail product line, as a concept demo
on SYNTHETIC data, qualitatively calibrated to the July 2026 memory-sector
unwind (SOX −19% in July 2026, its worst month since 2008).

⚠️  THIS IS A SYNTHETIC SCENARIO, NOT A HINDCAST ON REAL DATA AND NOT
    INVESTMENT ADVICE. Every path below is generated by the dual-noise +
    mean-field machinery of this repo. The July 2026 episode supplies the
    *narrative shape* (institutional crowding → LLM-homogenized retail
    chase → fundamental re-rating → forced unwind with retail capitulating
    at the bottom while institutions re-enter); the numbers are simulated.
    The real-data version of this demo is experiment E7 in RESOURCES.md.

The product thesis (To-C line):
    A retail investor cannot out-trade the behavioral noise ν_η — Theorem 1
    (dual Cramér-Rao) says nobody can. But the *equilibrium* component of
    the price — what the asset is worth once every agent has played its
    rational strategy — is exactly what the MFG solves for. Publish that
    denoised track and the divergence D_t = P_t/P_t^eq − 1 becomes a
    mid/long-horizon positioning signal: when the market trades 25% above
    its own equilibrium while the institutional mean field is already
    rotating out, you do not need to call the day of the crash — you need
    to not be the one buying the top.

Mechanics (same objects as the rest of the repo):
    P_t^eq  — equilibrium price: the MFG-consistent fundamental track.
              Steps down once, on the guidance shock (a Mode-I event
              operator: genuine information, Theorem 3 irreversibility).
    κ_t     — institutional crowding (Level-1/2 mean-field concentration).
    f_t     — retail flow: momentum-chasing, LLM-homogenized (Day 16).
    w_t     — the behavioral wedge: dw = a·(κ + b·f⁺) dt − c·w dt + jumps.
              Market price P_t = P_t^eq · (1 + w_t).
    Signal  — U_t fires when D_t > θ_D while the smoothed κ-trend has
              turned negative for ≥3 consecutive sessions: the wedge is
              large AND the agents holding it up are leaving.

Run:  python demo/denoised_price_2026.py  →  figures/denoised_price_demo.png
"""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
FIGS = os.path.join(os.path.dirname(HERE), "figures")

rng = np.random.default_rng(20260729)

# ── calendar ───────────────────────────────────────────────────────────────────
dates = pd.bdate_range(end="2026-07-29", periods=252)
n = len(dates)
t = np.arange(n)

GUIDANCE = pd.Timestamp("2026-07-13")   # HBM4-delay / guidance shock (Mode-I event)
UNWIND   = pd.Timestamp("2026-07-24")   # unwind accelerates (Korea selloff spillover)
CAPITUL  = pd.Timestamp("2026-07-28")   # capitulation session
i_guid   = dates.get_loc(GUIDANCE)
i_cap    = dates.get_loc(CAPITUL)

# ── equilibrium (denoised) price ───────────────────────────────────────────────
# Fundamental drift of an AI-memory franchise: strong but not manic.
mu_eq = 0.00055
eq_shock = np.zeros(n)
eq_shock[i_guid:] = np.log(1 - 0.06)          # −6% genuine re-rating at guidance
log_eq = np.log(100.0) + mu_eq * t + eq_shock \
         + np.cumsum(rng.normal(0, 0.0035, n))  # physical noise σ_τ only
P_eq = np.exp(log_eq)

# ── institutional crowding κ_t (mean-field concentration, Level 1–2) ───────────
# Logistic build-up through the AI-memory trade; institutions begin rotating
# out a few sessions BEFORE the guidance shock (they see the channel checks),
# and de-crowd hard after it.
kappa = 0.15 + 0.75 / (1 + np.exp(-(t - n * 0.55) / 18))
i_rot = i_guid - 4
decay = np.zeros(n)
decay[i_rot:] = np.linspace(0, 1, n - i_rot) ** 1.35
kappa = kappa - 0.55 * decay * kappa
kappa = np.clip(kappa + rng.normal(0, 0.008, n), 0.05, 0.95)
# Post-capitulation: institutions buy the dip (the AlphaGBM observation)
kappa[i_cap:] += np.linspace(0, 0.05, n - i_cap)

# ── retail flow f_t (LLM-homogenized momentum chase, Day 16) ───────────────────
mom = pd.Series(log_eq).diff(20).fillna(0).to_numpy()
h = 0.85                                        # homogenization coefficient
f = h * np.tanh(35 * mom) + rng.normal(0, 0.06, n)
f[i_guid:i_cap] += 0.25                         # retail buys the first dip…
f[i_cap:] = -0.9 + rng.normal(0, 0.05, n - i_cap)  # …then capitulates at the low

# ── behavioral wedge w_t ───────────────────────────────────────────────────────
w = np.zeros(n)
a, b, c = 0.0030, 0.55, 0.0105
for k in range(1, n):
    drive = a * (kappa[k] + b * max(f[k], 0.0))
    jump = 0.0
    if rng.uniform() < 0.04 + 0.10 * w[k - 1]:          # jumps cluster with crowding
        jump = rng.choice([-1, 1], p=[0.35, 0.65]) * rng.exponential(0.006)
    if k >= i_cap - 2:                                   # forced unwind: 4 sessions
        drive, c_eff = -0.055, 0.28
        jump = -abs(rng.normal(0.012, 0.006))
    else:
        c_eff = c
    w[k] = w[k - 1] + drive - c_eff * w[k - 1] + jump
w = np.clip(w, -0.08, 0.40)

P = P_eq * (1 + w)
D = P / P_eq - 1                                         # divergence

# ── the signal U_t ─────────────────────────────────────────────────────────────
THETA_D = 0.20
kap_trend = pd.Series(kappa).ewm(span=10).mean().diff()
falling = (kap_trend < 0).rolling(3).sum() == 3
armed = (pd.Series(D) > THETA_D) & falling.fillna(False)
sig_idx = armed[armed & (armed.index >= i_guid - 10)].index.min()
sig_date = dates[sig_idx]
lead_unwind = int(((dates > sig_date) & (dates <= UNWIND)).sum())
lead = int(((dates > sig_date) & (dates <= CAPITUL)).sum())

peak = P.max()
trough = P[i_cap - 2:].min()

print("=" * 70)
print("SYNTHETIC CONCEPT DEMO — denoised equilibrium price (To-C product line)")
print(f"scenario calendar : {dates[0].date()} → {dates[-1].date()}  ({n} sessions)")
print(f"guidance shock    : {GUIDANCE.date()}  (Mode-I operator, eq −6%)")
print(f"signal U_t fires  : {sig_date.date()}  —  D = {D[sig_idx]*100:+.1f}% above "
      f"equilibrium, κ-trend negative 3 sessions")
print(f"lead time         : {lead_unwind} trading days (≈2 weeks) before the "
      f"{UNWIND.date()} unwind acceleration,")
print(f"                    {lead} trading days before the {CAPITUL.date()} capitulation")
print(f"peak → trough     : {(trough/peak - 1)*100:.0f}%   "
      f"(market returns to its denoised track)")
print(f"at the trough     : retail flow f = {f[i_cap+1]:+.2f} (panic sell)  |  "
      f"institutional κ rising (buying the dip)")
print("=" * 70)

# ── figure ─────────────────────────────────────────────────────────────────────
OK = dict(blue="#0072B2", orange="#E69F00", red="#D55E00", ink="#111827",
          mute="#6B7280", grid="#E5E7EB")
plt.rcParams.update({"font.family": "sans-serif", "font.size": 10,
                     "axes.spines.top": False, "axes.spines.right": False,
                     "figure.facecolor": "white"})
fig, axes = plt.subplots(2, 1, figsize=(13.2, 7.6), sharex=True,
                         gridspec_kw=dict(height_ratios=[1.15, 1.0], hspace=0.10))
lo, hi = dates[0], dates[-1]

ax = axes[0]
ax.plot(dates, P, color=OK["ink"], lw=1.5, label="market price  $P_t$ (equilibrium + behavioral wedge)")
ax.plot(dates, P_eq, color=OK["blue"], lw=1.7,
        label="denoised equilibrium price  $P_t^{eq}$ (the product)")
ax.fill_between(dates, P_eq, P, where=P > P_eq, color=OK["orange"], alpha=0.25,
                label="behavioral wedge $w_t$ (crowding, Thm 1)")
ax.axvline(sig_date, color=OK["orange"], lw=1.5, ls="--")
ax.axvline(UNWIND, color=OK["red"], lw=1.0, ls=":")
ax.axvline(CAPITUL, color=OK["red"], lw=1.4, ls="--")
ax.annotate(f"{sig_date.strftime('%b %d')} — signal: price {D[sig_idx]*100:+.0f}% above\n"
            f"equilibrium while institutions rotate out.\n"
            f"{lead_unwind} trading days (≈2 weeks) before the\n"
            f"unwind accelerates on Jul 24.",
            xy=(sig_date, P[sig_idx]), xytext=(dates[int(n*0.35)], peak * 0.915),
            fontsize=9.5, fontweight="bold", color="#B45309",
            arrowprops=dict(arrowstyle="->", color="#B45309", lw=1.2))
ax.annotate("Jul 28 — capitulation:\nretail panic-sells at the low,\n"
            "institutions buy; price re-joins\nits denoised track.",
            xy=(CAPITUL, trough), xytext=(dates[int(n*0.46)], P_eq[0] * 0.985),
            fontsize=9.5, fontweight="bold", color=OK["red"],
            arrowprops=dict(arrowstyle="->", color=OK["red"], lw=1.2,
                            connectionstyle="arc3,rad=0.15"))
ax.axvline(GUIDANCE, color=OK["mute"], lw=0.9, ls=":")
ax.text(GUIDANCE - pd.Timedelta(days=3), 119.5, "guidance shock\nJul 13 (Mode-I)",
        fontsize=7.8, color=OK["mute"], ha="right")
ax.set_ylabel("price (indexed)")
ax.legend(loc="upper left", fontsize=8.5, frameon=False)
ax.set_title("Denoised equilibrium price — SYNTHETIC concept demo of the To-C product line "
             "(scenario shaped on the July 2026 memory unwind)",
             fontsize=12.5, fontweight="bold", loc="left", pad=10)
ax.grid(alpha=0.3)

ax = axes[1]
ax.plot(dates, D * 100, color=OK["ink"], lw=1.5, label="divergence  $D_t = P_t/P_t^{eq}-1$")
ax.axhline(THETA_D * 100, color=OK["red"], ls=":", lw=1.3)
ax.text(dates[int(n*0.42)], THETA_D * 100 + 1.2, f"θ_D = {THETA_D*100:.0f}%",
        fontsize=8.5, color=OK["red"])
ax.fill_between(dates, THETA_D * 100, np.clip(D * 100, THETA_D * 100, None),
                color=OK["orange"], alpha=0.45)
ax2 = ax.twinx()
ax2.plot(dates, kappa, color=OK["blue"], lw=1.3, alpha=0.85)
ax2.set_ylabel("institutional crowding  κ_t", color=OK["blue"])
ax2.tick_params(axis="y", labelcolor=OK["blue"])
ax2.spines.top.set_visible(False)
ax.axvline(sig_date, color=OK["orange"], lw=1.5, ls="--")
ax.axvline(CAPITUL, color=OK["red"], lw=1.4, ls="--")
ax.set_ylabel("divergence (%)")
ax.set_xlim(lo, hi)
ax.legend(loc="upper left", fontsize=8.5, frameon=False)
ax.grid(alpha=0.3)

fig.text(0.01, 0.005,
         "SYNTHETIC DATA — a concept demo of the denoised-price product, not investment advice and not "
         "a real-data hindcast. Signal U_t: D_t > θ_D while the EMA(10) κ-trend is negative 3 consecutive "
         "sessions. Real-data version: experiment E7 (RESOURCES.md).",
         fontsize=7.5, color=OK["mute"])
fig.savefig(os.path.join(FIGS, "denoised_price_demo.png"), dpi=200, bbox_inches="tight")
print("✓ figures/denoised_price_demo.png")
